apiVersion: 1

contactPoints:
  - orgId: 1
    name: telegram
    receivers:
      - uid: telegram
        type: telegram
        settings:
          bottoken: ${GRAFANA_TELEGRAM_BOT_TOKEN}
          chatid: ${GRAFANA_TELEGRAM_CHAT_ID}
          message: >-
            {{ template "default.message" . }}
