version: '3'

services:
  prometheus:
    image: prom/prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - internal-net

  grafana:
    image: grafana/grafana
    env_file:
      - ../../configs/monitor/.env.grafana
    volumes:
      - grafana_data:/var/lib/grafana
    networks:
      - web-shared-net
      - internal-net


  node-exporter:
    image: prom/node-exporter
    networks:
      - internal-net

volumes:
  grafana_data:

networks:
  web-shared-net:
    external: true
    name: web-network
  internal-net:
    driver: bridge
