services:
  nginx-proxy:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    env_file:
      - ../configs/ingress/.env.nginx
    volumes:
      - ../configs/ingress/certs:/etc/nginx/certs:ro 
      - ./templates:/etc/nginx/templates
    healthcheck:
      test: ["CMD-SHELL", "nginx -t"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 10s
    networks:
      - web-shared-net
    restart: always

networks:
  web-shared-net:
    external: true
    name: web-network
